/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package edu.berkeley.cs.zipg;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-07-31")
public class ThriftSrcAtype implements org.apache.thrift.TBase<ThriftSrcAtype, ThriftSrcAtype._Fields>, java.io.Serializable, Cloneable, Comparable<ThriftSrcAtype> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ThriftSrcAtype");

  private static final org.apache.thrift.protocol.TField SRC_FIELD_DESC = new org.apache.thrift.protocol.TField("src", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField ATYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("atype", org.apache.thrift.protocol.TType.I64, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ThriftSrcAtypeStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ThriftSrcAtypeTupleSchemeFactory());
  }

  public long src; // required
  public long atype; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    SRC((short)1, "src"),
    ATYPE((short)2, "atype");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // SRC
          return SRC;
        case 2: // ATYPE
          return ATYPE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __SRC_ISSET_ID = 0;
  private static final int __ATYPE_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.SRC, new org.apache.thrift.meta_data.FieldMetaData("src", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.ATYPE, new org.apache.thrift.meta_data.FieldMetaData("atype", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ThriftSrcAtype.class, metaDataMap);
  }

  public ThriftSrcAtype() {
  }

  public ThriftSrcAtype(
    long src,
    long atype)
  {
    this();
    this.src = src;
    setSrcIsSet(true);
    this.atype = atype;
    setAtypeIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ThriftSrcAtype(ThriftSrcAtype other) {
    __isset_bitfield = other.__isset_bitfield;
    this.src = other.src;
    this.atype = other.atype;
  }

  public ThriftSrcAtype deepCopy() {
    return new ThriftSrcAtype(this);
  }

  @Override
  public void clear() {
    setSrcIsSet(false);
    this.src = 0;
    setAtypeIsSet(false);
    this.atype = 0;
  }

  public long getSrc() {
    return this.src;
  }

  public ThriftSrcAtype setSrc(long src) {
    this.src = src;
    setSrcIsSet(true);
    return this;
  }

  public void unsetSrc() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __SRC_ISSET_ID);
  }

  /** Returns true if field src is set (has been assigned a value) and false otherwise */
  public boolean isSetSrc() {
    return EncodingUtils.testBit(__isset_bitfield, __SRC_ISSET_ID);
  }

  public void setSrcIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __SRC_ISSET_ID, value);
  }

  public long getAtype() {
    return this.atype;
  }

  public ThriftSrcAtype setAtype(long atype) {
    this.atype = atype;
    setAtypeIsSet(true);
    return this;
  }

  public void unsetAtype() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ATYPE_ISSET_ID);
  }

  /** Returns true if field atype is set (has been assigned a value) and false otherwise */
  public boolean isSetAtype() {
    return EncodingUtils.testBit(__isset_bitfield, __ATYPE_ISSET_ID);
  }

  public void setAtypeIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ATYPE_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case SRC:
      if (value == null) {
        unsetSrc();
      } else {
        setSrc((Long)value);
      }
      break;

    case ATYPE:
      if (value == null) {
        unsetAtype();
      } else {
        setAtype((Long)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case SRC:
      return getSrc();

    case ATYPE:
      return getAtype();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case SRC:
      return isSetSrc();
    case ATYPE:
      return isSetAtype();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ThriftSrcAtype)
      return this.equals((ThriftSrcAtype)that);
    return false;
  }

  public boolean equals(ThriftSrcAtype that) {
    if (that == null)
      return false;

    boolean this_present_src = true;
    boolean that_present_src = true;
    if (this_present_src || that_present_src) {
      if (!(this_present_src && that_present_src))
        return false;
      if (this.src != that.src)
        return false;
    }

    boolean this_present_atype = true;
    boolean that_present_atype = true;
    if (this_present_atype || that_present_atype) {
      if (!(this_present_atype && that_present_atype))
        return false;
      if (this.atype != that.atype)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_src = true;
    list.add(present_src);
    if (present_src)
      list.add(src);

    boolean present_atype = true;
    list.add(present_atype);
    if (present_atype)
      list.add(atype);

    return list.hashCode();
  }

  @Override
  public int compareTo(ThriftSrcAtype other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetSrc()).compareTo(other.isSetSrc());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSrc()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.src, other.src);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetAtype()).compareTo(other.isSetAtype());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAtype()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.atype, other.atype);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ThriftSrcAtype(");
    boolean first = true;

    sb.append("src:");
    sb.append(this.src);
    first = false;
    if (!first) sb.append(", ");
    sb.append("atype:");
    sb.append(this.atype);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ThriftSrcAtypeStandardSchemeFactory implements SchemeFactory {
    public ThriftSrcAtypeStandardScheme getScheme() {
      return new ThriftSrcAtypeStandardScheme();
    }
  }

  private static class ThriftSrcAtypeStandardScheme extends StandardScheme<ThriftSrcAtype> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ThriftSrcAtype struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // SRC
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.src = iprot.readI64();
              struct.setSrcIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // ATYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.atype = iprot.readI64();
              struct.setAtypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ThriftSrcAtype struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(SRC_FIELD_DESC);
      oprot.writeI64(struct.src);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(ATYPE_FIELD_DESC);
      oprot.writeI64(struct.atype);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ThriftSrcAtypeTupleSchemeFactory implements SchemeFactory {
    public ThriftSrcAtypeTupleScheme getScheme() {
      return new ThriftSrcAtypeTupleScheme();
    }
  }

  private static class ThriftSrcAtypeTupleScheme extends TupleScheme<ThriftSrcAtype> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ThriftSrcAtype struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetSrc()) {
        optionals.set(0);
      }
      if (struct.isSetAtype()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetSrc()) {
        oprot.writeI64(struct.src);
      }
      if (struct.isSetAtype()) {
        oprot.writeI64(struct.atype);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ThriftSrcAtype struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.src = iprot.readI64();
        struct.setSrcIsSet(true);
      }
      if (incoming.get(1)) {
        struct.atype = iprot.readI64();
        struct.setAtypeIsSet(true);
      }
    }
  }

}

