/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef succinct_graph_CONSTANTS_H
#define succinct_graph_CONSTANTS_H

#include "succinct_graph_types.h"



class succinct_graphConstants {
 public:
  succinct_graphConstants();

};

extern const succinct_graphConstants g_succinct_graph_constants;



#endif
