#export SUCCINCT_DATA_PATH="/mnt"
#export ISA_SAMPLING_RATE="8"
#export SA_SAMPLING_RATE="8"

export SHARDS_PER_SERVER=3
export TOTAL_NUM_SHARDS=3

# export SUCCINCT_HOST_SLEEP=120 # seconds
# export NUM_SHARDS_BATCH=16
