#export SUCCINCT_DATA_PATH="/mnt"
#export ISA_SAMPLING_RATE="8"
#export SA_SAMPLING_RATE="8"

k=8
export SHARDS_PER_SERVER=$k
export TOTAL_NUM_SHARDS=$k

export SHARDS_BATCH_SLEEP=120 # seconds
export NUM_SHARDS_BATCH=16
