#!/bin/bash

sbin="`dirname "$0"`"
sbin="`cd "$sbin"; pwd`"

usage() {
  echo "Usage: copy-dir <dir>"
  exit 1
}

if [[ "$#" != "1" ]] ; then
  usage
fi

if [[ ! -e "$1" ]] ; then
  echo "File or directory $1 doesn't exist!"
  exit 1
fi

DIR=`readlink -f "$1"`
DIR=`echo "$DIR"|sed 's@/$@@'`
DEST=`dirname "$DIR"`

HOSTS=`cat $sbin/zipg_clients`

SSH_OPTS="-o StrictHostKeyChecking=no -o ConnectTimeout=5"

echo "RSYNC'ing $DIR to hosts..."
for host in $HOSTS; do
  echo $host
  rsync -e "ssh $SSH_OPTS" -az "$DIR" "$host:$DEST" & sleep 0.5
done
wait
