/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "succinct_graph_constants.h"



const succinct_graphConstants g_succinct_graph_constants;

succinct_graphConstants::succinct_graphConstants() {
}



